name: Linux and macOS wheels

on: [push, pull_request, workflow_dispatch]

env:
  REPO_DIR: rasterio
  WHEEL_SDIR: wheelhouse
  CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-20.04", "macos-12" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        uses: pypa/cibuildwheel@v2.16
        with:
          output-dir: wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheels
      - name: Upload Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    needs: [build]
    runs-on: ubuntu-latest
    name: Wheels Successful
    steps:
      - name: Success
        run: echo Wheels Successful
